version: '3.9'

services:

  aspnet_core:
    container_name: aspnet_core
    ports:
      - "5000:5000"
      - "5001:5001"
    build: ./AspNetCore-keycloak/keycloakAuthDotNet6/.
    networks:
      - auth-network
   #   auth-network:
   #     ipv4_address: 10.11.0.4 # setting IPs directly to allow KC communication - KC doesn't seem to handle DNS resolution
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https_certs/aspnetapp.pfx 
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
    # pull value from docker-compose.env for CA fingerprint location
    env_file:
      - docker-compose.env
    volumes:
      - ./AspNetCore-keycloak/keycloakAuthDotNet6/certs:/https_certs:ro
      - ./shared_volume:/shared_volume

  keycloak_db:
    container_name: keycloak_db
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "6000:5432"
    networks:
      - auth-network

  keycloak_two:
    container_name: keycloak_two
    image: keycloak/keycloak
    ports: 
      - "8080:8080"
    depends_on:
      - keycloak_db
    environment:
      DB_VENDOR: "POSTGRES"
      DB_ADDR: keycloak_db
      DB_PORT: 6000
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: pass
    restart: always
    command: start-dev --https-certificate-file=/https_certs/keycloak.cert --https-certificate-key-file=/https_certs/keycloak.key
    networks:
      - auth-network
 #    auth-network:
 #       ipv4_address: 10.11.0.5
    volumes:
      - ./AspNetCore-keycloak/keycloakAuthDotNet6/certs:/https_certs:ro

# https://smallstep.com/docs/tutorials/docker-tls-certificate-authority/#manual-installation
# used as a CA to allow trust of keycloak certs
  smallstep_ca:
    container_name: smallstep_ca
    image: smallstep/step-ca
    ports:
      - "6783:6783"
      - "443:443"
    volumes:
      - ./step/passwords:/home/passwords
      - ./step/mount:/home/step
      - ./step/certs:/home/certs
      - ./step/scripts:/home/scripts
      - ./shared_volume:/shared_volume
    command: bash /home/scripts/init_smallstep.sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment: # doesn't seem to be being picked up
    # Specify a password for encrypted CA Keys & Default CA Provisioner
      DOCKER_STEPCA_INIT_PASSWORD: hello
    # pull value from docker-compose.env
    env_file:
    - docker-compose.env
    networks:
      - auth-network
 #     auth-network:
 #       ipv4_address: 10.11.0.6


networks:
  auth-network:
    driver: bridge
 #   ipam:
 ##     config:
  #      - subnet: 10.11.0.0/16
  #      - gateway: 10.11.0.0